import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppinsBold = Poppins({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-poppins"
});

const interRegular = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsBold.variable} ${interRegular.variable} antialiased`}
      >
        <Navbar />
          <main>{children}</main>
      </body>
    </html>
  );
}
