// I WILL DELETE THIS AFTER
// NOT NECESSARY
// FOR TESTING ONLY

import ModalProvider from "@/components/modals/providers";
import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";

const poppinsBold = Poppins({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-poppins"
});

const interRegular = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Kanang Kuan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsBold.variable} ${interRegular.variable} antialiased`}
      >
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
